### PR TITLE
Marked interfaces and blocks as API

### PR DESCRIPTION
**Pull request by shikhamis11**
The following interfaces and blocks should be marked as API

AdobeImsApi/Api/LogInInterface.php
AdobeImsApi/Api/LogOutInterface.php
Magento\AdobeIms\Block\Adminhtml\SignIn

### Fixed Issues (if relevant)

1. magento/adobe-ims#9: Mark interfaces and blocks as API
2. ...

**note**: Magento\AdobeIms\Block\Adminhtml\SignIn is already marked as API 

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-commerce/adobe-ims

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-commerce/adobe-ims` repository. Branch name: `imported-magento-adobe-ims-10`.

**Pull request merged**
